name: Wakarin.github.io
author: Kenta Yamazaki
url: https://wakarin.github.io
description: DeepLearning, linux, bike, ski, car

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
